name: dvb-scan

on:
  push:
    paths:
      - 'v4l-utils/dvb-scan/**'
      - '!v4l-utils/dvb-scan/**.md'
      - '.github/workflows/dvb-scan.yml'
  workflow_run:
    workflows: ["v4l-utils"]
    branches: [main]
    types:
      - completed

jobs:
  buildx:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - dvb-scan
        uses: docker/build-push-action@v2
        with:
          context: ./v4l-utils/dvb-scan
          file: ./v4l-utils/dvb-scan/Dockerfile
          tags: |
            ghcr.io/akashisn/dvb-scan
          platforms: linux/amd64,linux/arm64/v8
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache