name: epgstation

on:
  push:
    paths:
      - 'epgstation/**'
      - '!epgstation/**.md'
      - '.github/workflows/epgstation.yml'
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ffmpeg: [4.3.2, 4.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.workflow }}-${{ matrix.ffmpeg }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-${{ matrix.ffmpeg }}-

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - epgstation
        uses: docker/build-push-action@v2
        with:
          context: ./epgstation
          file: ./epgstation/Dockerfile
          tags: |
            ghcr.io/akashisn/dvb-docker/epgstation:${{ matrix.ffmpeg }}
          build-args: |
            FFMPEG_VERSION=${{ matrix.ffmpeg }}
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build and push - epgstation-qsv
        uses: docker/build-push-action@v2
        with:
          context: ./epgstation
          file: ./epgstation/qsv.Dockerfile
          tags: |
            ghcr.io/akashisn/dvb-docker/epgstation:${{ matrix.ffmpeg }}-qsv
          build-args: |
            FFMPEG_VERSION=${{ matrix.ffmpeg }}
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache